name: CI-Build-Push

on:
  push:
    branches: ["main"]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
        tar -xzf trivy_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/

    # üîç Scan backend Dockerfile
    - name: Scan Backend Dockerfile
      run: trivy config ./backend

    # üîç Scan frontend Dockerfile
    - name: Scan Frontend Dockerfile
      run: trivy config ./frontend

    # Build & Scan Backend Image
    - name: Build Backend Image
      run: docker build -t ${{ secrets.DOCKER_REPO_BACKEND }}:${{ github.sha }} ./backend

    - name: Scan Backend Image
      run: trivy image ${{ secrets.DOCKER_REPO_BACKEND }}:${{ github.sha }}

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_REPO_BACKEND }}:${{ github.sha }}

    # Build & Scan Frontend Image
    - name: Build Frontend Image
      run: docker build -t ${{ secrets.DOCKER_REPO_FRONTEND }}:${{ github.sha }} ./frontend

    - name: Scan Frontend Image
      run: trivy image ${{ secrets.DOCKER_REPO_FRONTEND }}:${{ github.sha }}

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_REPO_FRONTEND }}:${{ github.sha }}

    outputs:
      image_tag: ${{ github.sha }}
